### ISSUE TITLE
iTunMovi XML issue

### ISSUE THREAD

**Issue by bweav19** [jimevans/knuckleball#1]
For some reason Atomic Parsley or some library I used wants xml declarations in the iTunMovi Atom. This causes an issue in MovieInfo.cs  internal override void Populate(byte[] dataBuffer). I was trying to figure out the best way to handle this, seems like stripping it would be the best bet as it isn't needed from my understanding. I tried several things without much success. Thought I would run it by you as you might have a quick and easy way to ignore them.

Here is an example of the iTunMovi Atom I have problems with.

`<?xml version=1.0 encoding=UTF-8?> <!DOCTYPE plist http://www.apple.com/DTDs/PropertyList-1.0.dtd> <plist version=1.0> <dict> <key>cast</key> <array> <dict> <key>name</key> <string>Chris Farley</string> </dict> <dict> <key>name</key> <string> David Spade</string> </dict> <dict> <key>name</key> <string> Bo Derek</string> </dict> <dict> <key>name</key> <string> Brian Dennehy</string> </dict> <dict> <key>name</key> <string> Rob Lowe</string> </dict> <dict> <key>name</key> <string> Dan Aykroyd</string> </dict> </array> <key>directors</key> <array> <dict> <key>name</key> <string>Peter Segal</string> </dict> </array> <key>screenwriters</key> <array> <dict> <key>name</key> <string>Peter Segal</string> </dict> </array> <key>producers</key> <array> <dict> <key>name</key> <string>Lorne Michaels</string> </dict> </array> </dict> </plist>`

**Comment by bweav19** [comment]
Here is how I fixed it. Turns out the real problem is missing quotes around version,encoding etc. Also adjusted the Doctype to match what Knuckleball wrote into a file.

```
                StreamReader sreader = new StreamReader(stream);
                string data = sreader.ReadToEnd();
                if (data.Contains("<?xml version=1.0 encoding=UTF-8?>"))
                {
                    //string tempData = @data.Replace("<?xml version=1.0 encoding=UTF-8?>", string.Empty);
                    data = data.Replace("<?xml version=1.0 encoding=UTF-8?>", "<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                }
                if (data.Contains("<!DOCTYPE plist http://www.apple.com/DTDs/PropertyList-1.0.dtd>"))
                {
                    //tempData = @tempData.Replace("<!DOCTYPE plist http://www.apple.com/DTDs/PropertyList-1.0.dtd>", string.Empty);
                    data = data.Replace("<!DOCTYPE plist http://www.apple.com/DTDs/PropertyList-1.0.dtd>", "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">");
                }
                if (data.Contains("<plist version=1.0>"))
                {
                    data = data.Replace("<plist version=1.0>", "<plist version=\"1.0\">");
                }

                byte[] byteArray = Encoding.UTF8.GetBytes(data.Trim());
                MemoryStream cleanStream = new MemoryStream(byteArray);
                stream = cleanStream;
```

**Comment by jimevans** [comment]
Can you provide a file with the iTunMOVI atom set this way? If your analysis is correct, the other library is writing invalid XML into the atom, and the .NET XmlTextReader may not be able to handle the malformed XML that easily.

**Comment by jimevans** [comment]
Actually, the more I think about it, I'm not sure how you'd expect the library to handle this. The atom is supposed to contain valid XML, and I what you'd expect Knuckleball to do with invalid XML, since the XmlTextReader chokes on it.

**Comment by bweav19** [comment]
Agreed not sure how it happened never looked closely at it as the cast etc showed up fine in iTunes so Apple isn't even checking it apprently. I was using someone else's code to feed the tags to Atomic Parsley and it looks correct, has the quotes in it, end result was wrong.

Entirely up to you as for a genric fix my thoughts....

Knuckleball could Catch an XML error and return null cast,producers, etc. ?  Right now it just causes opening the file to generate an exception and stop. 

Also maybe provide a way to get the Raw Atom so some additional attempt at processing could be made?

**Comment by bweav19** [comment]
Closing, I've made a specific fix for my situation.
